[package]
name = "basicGame"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = { version = "0.4", features = ["audio"] }
macroquad-particles = "0.2.2"
quad-storage = "0.1.0"

[profile.dev.package.'*']
opt-level = 3
